# -*- coding: utf-8 -*-
"""robo.sinanlab.com 占位页 v0：即将上线 + 首批模型预览（来自 seed_v0.json，未核实字段一律标徽标）+ 订阅。Sprint 0 正式版按任务书用 Astro 做。"""
import io, os, json
D=json.load(open("data/seed_v0.json")); os.makedirs("public",exist_ok=True)
def v(x): 
    if x is None: return '<span class="todo">待核实</span>'
    s=str(x)
    return s.replace("待核实",'<span class="todo">待核实</span>').replace("(","<span class=\"dim\">(").replace(")",")</span>")
rows="".join(f'<tr><td><b>{m["name"]}</b><div class="dim">{m["org"]}</div></td><td>{v(m.get("params_b"))}{"" if m.get("params_b") is None else " B"}</td><td>{v(m["arch_type"])}</td><td>{v(m["license"])}</td><td>{"、".join(m.get("target_embodiments") or []) or v(None)}</td><td class="num">{len(m.get("evidence") or [])}</td></tr>' for m in D["models"])
emb="".join(f'<tr><td><b>{e["name"]}</b><div class="dim">{e["vendor"]}</div></td><td>{e["form"]}</td><td>{v(e.get("dof"))}</td><td>{v(e["price_range_cny"])}</td></tr>' for e in D["embodiments"])
html=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sinan Robo · 司南·机脑 —— 开源具身模型的可审计索引（即将上线）</title><meta name="description" content="司南实验室出品。开源 VLA 模型 × 本体适配矩阵、硬件延迟与推理成本。每个字段带来源，未核实一律标注。"><link rel="canonical" href="https://robo.sinanlab.com/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta name="theme-color" content="#0B0F14"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&family=Noto+Serif+SC:wght@600;700&display=swap"><style>
:root{{--ground:#0B0F14;--surface:#10161E;--hair:#1F2A36;--hair2:#2A3644;--ink:#E8EEF3;--ink2:#A3B1BE;--ink3:#64768A;--robo:#E0AE4A;--accent:#4FD1D9}}*{{box-sizing:border-box}}body{{margin:0;background:var(--ground);color:var(--ink);font-family:"IBM Plex Sans","PingFang SC",system-ui,sans-serif;font-size:14.5px;line-height:1.6}}a{{color:var(--robo);text-decoration:none}}.wrap{{max-width:1120px;margin:0 auto;padding:0 32px}}header{{border-bottom:1px solid var(--hair)}}.bar{{display:flex;align-items:center;gap:20px;padding:22px 0}}.bar nav{{margin-left:auto;display:flex;gap:20px;font-size:14px}}.bar nav a{{color:var(--ink2)}}.serif{{font-family:"Instrument Serif","Noto Serif SC",serif;font-weight:400}}.mono{{font-family:"JetBrains Mono",monospace}}.eyebrow{{font-family:"JetBrains Mono",monospace;font-size:11px;letter-spacing:.22em;color:var(--robo);text-transform:uppercase}}h1{{margin:0;font-size:22px}}h2{{margin:14px 0 0;font-size:48px;line-height:1.06;letter-spacing:-.01em;text-wrap:balance}}h2 em{{color:var(--robo)}}p.lead{{font-size:16px;color:var(--ink2);max-width:660px;margin:16px 0 0}}main{{padding:52px 0 80px}}.sec{{margin-top:44px}}.sec h3{{font-family:"Instrument Serif","Noto Serif SC",serif;font-size:26px;margin:0 0 12px;font-weight:400}}.card{{background:var(--surface);border:1px solid var(--hair);border-radius:14px;overflow:hidden}}table{{width:100%;border-collapse:collapse;font-size:13.5px}}th{{font-family:"JetBrains Mono",monospace;font-size:10px;letter-spacing:.16em;color:var(--ink3);text-transform:uppercase;text-align:left;padding:10px 16px;border-bottom:1px solid var(--hair);font-weight:500}}td{{padding:11px 16px;border-bottom:1px solid #141C25;vertical-align:top}}tr:last-child td{{border-bottom:0}}td.num{{font-family:"JetBrains Mono",monospace;text-align:right}}.dim{{color:var(--ink3);font-size:12px}}.todo{{display:inline-block;font-family:"JetBrains Mono",monospace;font-size:10.5px;padding:1px 7px;border-radius:999px;background:rgba(224,174,74,.14);color:var(--robo)}}.notice{{border:1px solid rgba(224,174,74,.35);background:rgba(224,174,74,.08);border-radius:12px;padding:14px 18px;color:var(--ink2);font-size:13.5px;margin-top:18px}}form.sub{{display:flex;gap:10px;margin-top:16px;max-width:520px}}form.sub input{{flex:1;height:44px;border:1px solid var(--hair2);border-radius:9px;background:var(--surface);color:var(--ink);padding:0 14px;font:inherit}}form.sub button{{height:44px;border:0;border-radius:9px;background:var(--robo);color:#1A1204;font:inherit;font-weight:600;padding:0 18px;cursor:pointer}}footer{{border-top:1px solid var(--hair)}}footer .wrap{{display:flex;flex-wrap:wrap;gap:20px;padding:22px 32px;font-size:12.5px;color:var(--ink3)}}footer a{{color:var(--ink3)}}@media(max-width:800px){{h2{{font-size:34px}}.bar nav{{display:none}}}}
</style></head><body>
<header><div class="wrap bar"><a href="/" style="display:flex;align-items:center;gap:12px;color:var(--ink)"><svg width="30" height="30" viewBox="0 0 40 40"><circle cx="20" cy="20" r="17.5" fill="none" stroke="#2A3644" stroke-width="1.2"/><path d="M20 9 L24.5 20 L20 31 Z" fill="#E0AE4A"/><path d="M20 9 L15.5 20 L20 31 Z" fill="#2A3644"/><circle cx="20" cy="20" r="2.2" fill="#0B0F14" stroke="#E0AE4A" stroke-width="1.4"/></svg><div><h1 class="serif">Sinan Robo</h1><div class="mono" style="font-size:10px;letter-spacing:.22em;color:var(--ink3)">司南·机脑 · SINAN LAB</div></div></a><nav><a href="https://compute.sinanlab.com">Sinan Compute</a><a href="https://sinanlab.com/constitution.html">中立宪法</a><a href="https://sinanlab.com">← 司南实验室</a></nav></div></header>
<main><div class="wrap">
<div class="eyebrow">即将上线 · Sprint 0 进行中</div><h2 class="serif">开源具身模型的<em>可审计索引。</em></h2>
<p class="lead">模型 × 本体适配矩阵、硬件延迟与推理成本、方法论公开。每个字段带来源；<b style="color:var(--ink)">没核实的一律标"待核实"，不猜、不填默认值。</b></p>
<div class="notice">下面是首批种子数据的原样预览：{len(D["models"])} 个模型、{len(D["embodiments"])} 个本体、{len(D["hardware"])} 种硬件。黄色徽标就是我们还没核实的字段——上线前至少补齐前 5 个模型的许可证与权重链接。</div>
<section class="sec"><h3>首批模型</h3><div class="card"><table><thead><tr><th>模型</th><th>参数量</th><th>架构</th><th>许可证</th><th>目标本体</th><th style="text-align:right">证据条数</th></tr></thead><tbody>{rows}</tbody></table></div></section>
<section class="sec"><h3>首批本体</h3><div class="card"><table><thead><tr><th>本体</th><th>形态</th><th>自由度</th><th>参考价</th></tr></thead><tbody>{emb}</tbody></table></div></section>
<section class="sec"><h3>上线时通知我</h3><p style="color:var(--ink2);margin:0">首期《机脑行情》：LingBot-VLA 2.0、GR00T N1.7、星海图 WRC 开源前瞻。</p><form class="sub" action="https://buttondown.com/api/emails/embed-subscribe/sinanlab" method="post" target="_blank"><input type="email" name="email" placeholder="you@company.com" required><button type="submit">订阅</button></form><p class="dim" style="margin-top:8px">订阅服务接入中，正式地址上线前替换。</p></section>
</div></main>
<footer><div class="wrap"><span>© 2026 Sinan Lab · 司南实验室</span><a href="https://sinanlab.com/constitution.html">中立宪法</a><a href="https://sinanlab.com/privacy.html">隐私政策</a><a href="https://sinanlab.com/disclaimer.html">免责声明</a><a href="mailto:hello@sinanlab.com">hello@sinanlab.com</a><span style="margin-left:auto">种子数据 v0 · 2026-08-31 · 每个字段带 evidence</span></div></footer></body></html>'''
io.open("public/index.html","w",encoding="utf-8").write(html)
io.open("public/robots.txt","w").write("User-agent: *\nAllow: /\n")
io.open("public/favicon.svg","w").write('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="8" fill="#0B0F14"/><circle cx="20" cy="20" r="14" fill="none" stroke="#2A3644" stroke-width="1.5"/><path d="M20 9 L24.5 20 L20 31 Z" fill="#E0AE4A"/><path d="M20 9 L15.5 20 L20 31 Z" fill="#2A3644"/><circle cx="20" cy="20" r="2.2" fill="#0B0F14" stroke="#E0AE4A" stroke-width="1.4"/></svg>')
print("robo 占位页生成：%d 模型 / %d 本体" % (len(D["models"]), len(D["embodiments"])))
